version: "3.9"
services:
  kong:
    image: kong:3.0.0-alpine
    environment:
      KONG_DATABASE: 'off'
      KONG_PROXY_ACCESS_LOG: '/dev/stdout'
      KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
      KONG_PROXY_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_LISTEN: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
      KONG_DECLARATIVE_CONFIG: '/home/kong/kong.yml'
    volumes:
      - "./kong/kong.yml:/home/kong/kong.yml:ro" # use `kong config init PATH` to create default tempalte file
      - "./kong/pubkey.pem:/home/kong/pubkey.pem:ro"
      - "./kong/jwt-private.pem:/home/kong/jwt-private.pem:ro"
      - "./kong/jwt-public.pem:/home/kong/jwt-public.pem:ro"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
  kong-ui:
    image: pocketdigi/kong-admin-ui:0.5.3
    ports:
      - "8899:80"
  dummy:
    image: node:18-alpine
    command: ['node', '/home/node/dummy/index.js']
    volumes:
      - "./dummy:/home/node/dummy:ro"
